### PR TITLE
Feat/split service runtime backlight

### PR DESCRIPTION
**Pull request by JeffLabonte**
Increased test coverage to 75% of the source code. 

Create a new Class to handle the loop actions when running as a service. `KeyboardBacklight` should be used as an API for the UI (Most of the logic related to the keyboards and basic interactions are in `KeyboardBacklight`.

Tested against my Oryx Pro 6, it works like a charm.

@ahoneybun You can test it by running `make install` and running as root `system76-brightness-manager`.

### CODE REVIEW

**Comment by ahoneybun** [comment]
Will do in a bit ! 🖖

**Comment by ahoneybun** [comment]
`    ~/git/System76-Backlight-Manager-cli    main  sudo system76-backlight-manager                                                      ✔  7s  
Starting Service
Traceback (most recent call last):
  File "/usr/bin/system76-backlight-manager", line 33, in <module>
    sys.exit(load_entry_point('system76-backlight-manager==0.1', 'console_scripts', 'system76-backlight-manager')())
  File "/usr/lib/python3.9/site-packages/system76_backlight_manager-0.1-py3.9.egg/system76_backlight_manager/__main__.py", line 50, in main
  File "/usr/lib/python3.9/site-packages/system76_backlight_manager-0.1-py3.9.egg/system76_backlight_manager/keyboard_backlight.py", line 60, in run
  File "/usr/lib/python3.9/site-packages/system76_backlight_manager-0.1-py3.9.egg/system76_backlight_manager/keyboard_backlight.py", line 64, in breathe
  File "/usr/lib/python3.9/site-packages/system76_backlight_manager-0.1-py3.9.egg/system76_backlight_manager/keyboard_backlight.py", line 81, in _ramp_up
  File "/usr/lib/python3.9/site-packages/system76_backlight_manager-0.1-py3.9.egg/system76_backlight_manager/keyboard_backlight.py", line 102, in _read_brightness
  File "/usr/lib/python3.9/site-packages/system76_backlight_manager-0.1-py3.9.egg/system76_backlight_manager/common.py", line 7, in read_file
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/leds/system76_acpi::kbd_backlight/brightness'
`

It looks like it doesn't check dmidecode to remove system76_acpi with system76 for the oryp4.

**Comment by JeffLabonte** [comment]
@ahoneybun you are not running the good version . So it seems. Before running `make install`, run `sudo pip uninstall system76-backlight-manager`.

**Comment by ahoneybun** [comment]
That's odd since I just cloned it, installed it and ran it for the first time today. I'll try those steps now.

**Comment by ahoneybun** [comment]
I'm getting the same output.

**Comment by JeffLabonte** [comment]
@ahoneybun What branch are you on? You need to be on `feat/split_service_runtime_backlight`

**Comment by ahoneybun** [comment]
Ah that would do it.

**Comment by ahoneybun** [comment]
Sorry I had a Sunday moment lol.

**Comment by ahoneybun** [comment]
So it has been at 'Starting Service' for a while. Anything I should be doing?

**Comment by JeffLabonte** [comment]
@ahoneybun You should notice that your keyboard backlight does the breathing effect and turned to green if your battery is over 50%

**Comment by ahoneybun** [comment]
Ah it is indeed breathing! I'm at 95% so that matches!

**Review by ahoneybun — APPROVED** [review]
Works as it should with the breathing effect and sets the keyboard green if over 50% battery life.

**Comment by JeffLabonte** [comment]
@ahoneybun Great! We can merge this. I will work on implementing something to control the services so we can start them from the UI and have the breathing effect working.

**Comment by JeffLabonte** [comment]
@ahoneybun Thank you for your QA :smile:

**Comment by ahoneybun** [comment]
Sorry for the slow movement with my brain lol.

**Pull request merged**
